name: Era
options:
  bundleIdPrefix: de.malte
targets:
  Era:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: Sources
        excludes:
          - "Widget/**"
          - "Resources/**/*.lproj/**"
      - path: Sources/Resources
        buildPhase: resources
    info:
      path: Sources/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: de.malte.era
        PRODUCT_NAME: Era
        MARKETING_VERSION: "27.0.3"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: YES
        DERIVE_MACCATALYST_PRODUCT_BUNDLE_IDENTIFIER: NO
        CODE_SIGN_STYLE: Automatic
    entitlements:
      path: Sources/Era.entitlements
  EraShareExtension:
    type: app-extension
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: ShareExtension
    info:
      path: ShareExtension/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: de.malte.era.share
        PRODUCT_NAME: EraShareExtension
        MARKETING_VERSION: "27.0.3"
        SUPPORTS_MACCATALYST: YES
        DERIVE_MACCATALYST_PRODUCT_BUNDLE_IDENTIFIER: NO
        GENERATE_INFOPLIST_FILE: NO
        CODE_SIGN_STYLE: Automatic
    dependencies:
      - target: Era
